<!-- XML with internal DTD for following specs
a. User(root)
    i. Name(child)
    ii. Address(child)
        1. District (sub-child)
        1. Location (sub-child) -->

<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE User[
<!ELEMENT User (Name, Address)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (District, Location)>
<!ELEMENT District (#PCDATA)>
<!ELEMENT Location (#PCDATA)>
]>
<User>
    <Name>Nischal Shrestha</Name>
    <Address>
        <District>Kathmandu</District>
        <Location>Samakhushi</Location>
    </Address>
</User>