<!-- XML with internal DTD for following specs
a. Users with multiple User
b. User(root)
    i. Name(child)
    ii. Address(child)
        1. District (sub-child)
        1. Location (sub-child) -->

<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE Users[
<!ELEMENT Users (User+)>
<!ELEMENT User (Name, Address)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (District, Location)>
<!ELEMENT District (#PCDATA)>
<!ELEMENT Location (#PCDATA)>
]>
<Users>
    <User>
        <Name>Nischal Shrestha</Name>
        <Address>
            <District>Kathmandu</District>
            <Location>Samakhushi</Location>
        </Address>
    </User>
    <User>
        <Name>Niraj Shrestha</Name>
        <Address>
            <District>Kathmandu</District>
            <Location>Banasthali</Location>
        </Address>
    </User>
    <User>
        <Name>John Richard</Name>
        <Address>
            <District>Lalitpur</District>
            <Location>Sanepa</Location>
        </Address>
    </User>
</Users>